FROM armhf/alpine:3.5
RUN apk add --no-cache nodejs

ADD https://github.com/alexellis/faas/releases/download/0.5.3-alpha/fwatchdog-armhf /usr/bin/fwatchdog
RUN chmod +x /usr/bin/fwatchdog

WORKDIR /root/

COPY package.json .

# Provides a boot-strap into your function, just add handler.js to derived image
RUN npm i
COPY faas_index.js .

ENV fprocess="node faas_index.js"

HEALTHCHECK --interval=5s CMD [ -e /tmp/.lock ] || exit 1

CMD ["fwatchdog"]
