curators:
 - alexellis
 - LucasRoesler
 - martindekov
 - utsavanand2
 - viveksyngh
 - Waterdrips

features:
 - dco_check
 - comments
 - pr_description_required
 - release_notes
# - hacktoberfest
# - no_newbies # Newbies are welcome, however there is some automation that will affect you during October. You are welcome, please be patient with us.

contributing_url: https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md

required_in_issues:
  - "## Expected Behaviour"
  - "## Current Behaviour"
  - "## Possible Solution"
  - "## Steps to Reproduce (for bugs)"
  - "## Context"
  - "## Your Environment"

custom_messages:
  - name: slack
    value: |
           --
           Join Slack to connect with the community
           https://docs.openfaas.com/community

  - name: template
    value: |
           Thank you for your interest in the project.
           
           By participating in the community, you are agreeing to follow the contribution guidelines.

           This project uses templates for new Issues and Pull Requests. These templates contain information that the team needs you to provide, before they can help.
           
           You are receiving this message because you chose to delete the template instead of filling it in as required by the project maintainers.

           Please go ahead and edit this Issue or Pull Request and please provide all the fields that were requested. If it is simpler, you may open a new Issue or Pull Request or find the text within the `.github` folder in this repository.

  - name: propose
    value: |
           This project follows a contributing guide which states that all
           changes must be proposed with an Issue before being worked on.
           
           Please raise an Issue and update your Pull Request to include
           the ID or link as part of the description.

           Thank you for your contribution.

  - name: test
    value: |
           This project follows a contributing guide which requires that
           all changes are tested before being merged. You should include
           worked examples that a maintainer can run to prove that the
           changes are good.

           Screenshots and command line output are also accepted, but
           must show the positive, and negative cases, not just that 
           what was added worked as you expected.

           Thank you for your contribution.

  - name: enduser
    value: |
           Thank you for your interest in OpenFaaS. This project is maintained and made available for hobbyists and commercial users alike, so we need to balance our time across everyone's needs. Whilst we are excited in your interest in using OpenFaaS, we would also ask you to take a look at our contribution guide on [Setting expectations, support and SLAs](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md#setting-expectations-support-and-slas).
           
           Commercial users can purchase [support](https://openfaas.com/support) in order to get dedicated help from OpenFaaS Ltd, or they can book ad-hoc consulting hours to get an engineer to dedicate time to helping them.
           
           If that is not a good fit for you at this time, please check out the OpenFaaS [GitHub Sponsors](https://github.com/sponsors/openfaas) options which are priced for practitioners like yourself. Organisations can also sponsor through their GitHub billing relationship.
           
           When you become a sponsor as an indvidual, it will show this on your issues and PRs, so that the community can see that you are supporting our work, and can prioritise your needs.
           
           If you are receiving this message after having received hands-on support from the OpenFaaS community, please join [GitHub Sponsors](https://github.com/sponsors/openfaas) to say thank you for our time. 
           
           Thank you for supporting OpenFaaS.
