maintainers:
 - alexellis
 - stefanprodan
 - rgee0
 - johnmccabe
 - LucasRoesler
 - BurtonR
 - kenfdev
 - ivanayov
 - viveksyngh
 - martindekov
 - ewilde
 - bartsmykla
 - s8sg
 - affix

features:
 - dco_check
 - comments
 - pr_description_required

contributing_url: https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md
