version: "3"
services:

    # Calculates base64 representation of request body.
    windows:
        image: stefanscherer/base:golang-1.7.5-windows
        labels:
            function: "true"
        depends_on:
            - gateway
        networks:
            - functions
        environment:
            fprocess: "app.exe"
            no_proxy: "gateway"
            https_proxy: $https_proxy
        deploy:
            placement:
                constraints: [node.platform.OS == windows]

networks:
    functions:
        driver: overlay
        # Docker does not support this option yet - maybe create outside of the stack and reference as "external"?
        #attachable: true
