version: "3"
services:
    gateway:
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
            - 8080:8080
        image: alexellis2/faas-gateway:latest-armhf
        networks:
        - functions

    prometheus:
        image: alexellis2/prometheus-armhf:latest
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command: "-config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -storage.local.memory-chunks=10000"
        ports:
            - 9090:9090
        depends_on:
            - gateway
        environment:
            no_proxy:   "gateway"
        networks:
            - functions

networks:
    functions:
        driver: overlay
        # Docker does not support this option yet - maybe create outside of the stack and reference as "external"?
        #attachable: true
