FROM golang:1.7.5
# RUN mkdir -p /go/src/github.com/alexellis/faas/gateway
WORKDIR /go/src/github.com/alexellis/faas/gateway

COPY vendor         vendor

COPY handlers       handlers
COPY metrics        metrics
COPY requests       requests
COPY tests          tests
COPY server.go      .
COPY readconfig.go  .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o gateway .

