FROM golang:1.7.5-windowsservercore
MAINTAINER alexellis2@gmail.com

ENTRYPOINT []


WORKDIR /go/src/github.com/alexellis/faas/sample-functions/golang

COPY . /go/src/github.com/alexellis/faas/sample-functions/golang


RUN go install

