FROM armhf/alpine:latest
RUN apk --update add nodejs

COPY fwatchdog /usr/bin

RUN chmod +x /usr/bin/fwatchdog

COPY package.json .
COPY main.js .
RUN npm i
ENV fprocess="node main.js"
CMD ["fwatchdog"]
