FROM openfaas/classic-watchdog:0.18.8 as watchdog

FROM arm32v6/alpine:3.11

RUN apk --no-cache add imagemagick

COPY --from=watchdog /fwatchdog /usr/bin/fwatchdog
RUN chmod +x /usr/bin/fwatchdog

ENV fprocess "convert - -resize 50% fd:1"

RUN addgroup -g 1000 -S app && adduser -u 1000 -S app -G app
USER 1000

EXPOSE 8080

HEALTHCHECK --interval=1s CMD [ -e /tmp/.lock ] || exit 1
CMD [ "/usr/bin/fwatchdog"]