FROM golang:1.7.5-windowsservercore
RUN mkdir -p /go/src/github.com/alexellis/faas/watchdog
WORKDIR /go/src/github.com/alexellis/faas/watchdog

COPY main.go        .
COPY readconfig.go  .
COPY config_test.go .
COPY requesthandler_test.go .
COPY types types

RUN go test
env CGO_ENABLED=0
env GOOS=windows
RUN go build -a -installsuffix cgo -o watchdog .
